//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pista
    {
        public int ID { get; set; }
        public string varchNombre { get; set; }
        public Nullable<int> intDuracion { get; set; }
        public int IDDisco { get; set; }
    
        public virtual Disco Disco { get; set; }
    }
}
