//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Disco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Disco()
        {
            this.Pistas = new HashSet<Pista>();
        }
    
        public int ID { get; set; }

        [DisplayName("Foto de portada")]
        public byte[] varbPortada { get; set; }

        [HiddenInput(DisplayValue = false)]
        public string nvarchImageMimeType { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "El nombre del álbum no puede estar vacío.")]
        [DisplayName("Nombre del álbum")]
        public string varchNombre { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "El año de lanzamiento no puede estar vacío.")]
        [Range(1900, 2019, ErrorMessage = "El año debe estar comprendido entre 1900 y 2019.")]
        [DisplayName("Año de lanzamiento")]
        public int intAño { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "El intérprete no puede estar vacío.")]
        [DisplayName("Intérprete")]
        public int IDArtista { get; set; }
    
        public virtual Artista Artista { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pista> Pistas { get; set; }
    }
}
